version: "3.4"
services:
  service:
    build:
      context: .
      target: development
    ports:
      - "9000:9000" # development
      - "8080:8080" # production
      - "35729:35729" # livereload
      - "5858:5858" # debugger
      - "9229:9229" # profiler
    working_dir: &PROJECT_ROOT_DIR /app
    # linux permissions: we must explicitly run as the node user
    user: node
    volumes:
      # mount working directory
      # https://docs.docker.com/docker-for-mac/osxfs-caching/#delegated
      # the container’s view is authoritative (permit delays before updates on the container appear in the host)
      - .:/app:delegated

      # mount cached vscode container extensions
      # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
      - vscode-extensions:/home/node/.vscode-server/extensions
      - vscode-extensions-insiders:/home/node/.vscode-server-insiders/extensions

    environment:
      # Set your key in the .gitignored .env file.
      GOOGLE_FONTS_API_KEY: ${GOOGLE_FONTS_API_KEY}

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  # vscode: Avoiding extension reinstalls on container rebuild
  # https://code.visualstudio.com/docs/remote/containers-advanced#_avoiding-extension-reinstalls-on-container-rebuild
  vscode-extensions:
  vscode-extensions-insiders:
